# Generated by Django 4.2.3 on 2023-08-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateField(blank=True, default=datetime.date(2023, 8, 26), null=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='состояние')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
