# Generated by Django 4.2.3 on 2023-08-27 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 27), null=True, verbose_name='дата создания'),
        ),
    ]
