# Generated by Django 4.2.3 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('surname', models.CharField(max_length=150, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('first_name', 'last_name', 'surname'),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')),
                ('try_status', models.CharField(max_length=250, verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
                'ordering': ('last_try_date',),
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='письмо')),
                ('time', models.TimeField(verbose_name='время  начала рассылки')),
                ('mailing_periodicity', models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month')], max_length=40, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('c', 'create'), ('s', 'start'), ('f', 'finish')], default='c', max_length=20, verbose_name='cтатус')),
                ('mailing_is_active', models.BooleanField(default=True, verbose_name='Рассылка активна')),
                ('clients', models.ManyToManyField(to='servise.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылок',
                'ordering': ('mailing_status',),
            },
        ),
    ]
